from __future__ import annotations

from dataclasses import dataclass, field

from kernel_v3.contracts import Contract, JsonObject, ToolManifest


SAFE_SEMANTIC_CAPABILITIES = frozenset(
    {
        "conversation.respond",
        "user.ask",
        "roleplay.perform",
        "knowledge.explain",
        "analysis.reason",
        "task.decompose",
        "research.plan",
        "decision.support",
        "strategy.assess",
        "personal_assistant.coordinate",
        "preference.apply",
        "quality.review",
        "legal.information",
        "medical.information",
        "education.tutor",
        "creative.write",
        "communication.draft",
        "document.draft",
        "document.review",
        "report.compose",
        "email.draft",
        "operations.plan",
        "product.analysis",
        "risk.compliance_review",
        "cybersecurity.review",
        "web.research",
        "finance.fundamentals_research",
        "finance.market_news",
        "finance.market_data",
        "finance.macro_data",
        "finance.competitive_landscape",
        "finance.source_directory",
        "finance.verify_numeric",
        "academic.research",
        "academic.frontier_research",
        "academic.literature_review",
        "academic.paper_search",
        "academic.scholarly_sources",
        "technical.documentation_research",
        "technical.api_documentation",
        "technical.developer_docs",
        "technical.source_repository",
        "retrieval.run",
        "calculator.compute",
        "workspace.list",
        "workspace.search",
        "file.read",
        "workspace.write",
        "workspace:read",
        "workspace:write",
        "durable_memory.read",
        "durable_memory.search",
        "durable_memory.propose",
        "memory.recall",
        "artifact.create",
        "artifact.read",
        "data.table.analyze",
        "chart.generate",
        "project.plan",
        "project.status",
        "workflow.automation.plan",
        "system.time",
        "system.environment",
    }
)


@dataclass(frozen=True, kw_only=True)
class CapabilitySpec(Contract):
    capability_id: str
    family: str
    status: str
    description: str
    tool_name: str | None = None
    side_effect_class: str = "none"
    permissions_required: list[str] = field(default_factory=list)
    enabled_by_default: bool = False
    metadata: JsonObject = field(default_factory=dict)


def capability_catalog(
    *,
    tool_manifests: list[ToolManifest] | None = None,
    allowed_tools: list[str] | None = None,
    allowed_permissions: set[str] | None = None,
    mode: str | None = None,
) -> JsonObject:
    manifests = {manifest.name: manifest for manifest in tool_manifests or []}
    allowed_tool_set = set(allowed_tools or [])
    allowed_permission_set = set(allowed_permissions or set())
    specs = _base_capabilities()
    specs.extend(_tool_capabilities(manifests, allowed_tool_set, allowed_permission_set))
    return {
        "version": 1,
        "mode": mode,
        "families": _family_summary(specs),
        "capabilities": [spec.to_dict() for spec in specs],
        "executable_tools": [
            spec.tool_name
            for spec in specs
            if spec.tool_name and spec.status in {"enabled", "available_with_permission"}
        ],
        "not_configured": [spec.capability_id for spec in specs if spec.status == "not_configured"],
        "planned": [spec.capability_id for spec in specs if spec.status == "planned"],
    }


def semantic_capability_catalog() -> JsonObject:
    return {
        "version": 1,
        "modes": [
            "direct_answer",
            "semantic_answer",
            "retrieval_answer",
            "workspace_answer",
            "workspace_write",
            "system_answer",
            "clarify_first",
        ],
        "core_rule": "The model proposes capabilities/actions; the host validates policy, executes tools, journals, and stops.",
        "catalog_rule": (
            "Choose semantic intent labels freely, but use these capability ids "
            "for executable or blocked host boundaries. Planned/host_only "
            "capabilities describe state and future surfaces; they are not tools."
        ),
        "state_dimensions": {
            "task_lifecycle": ["new_task", "continue_task", "ask_user_pending", "finalizing", "failed", "blocked"],
            "workloop": ["planning", "executing", "observing", "evaluating_progress", "replanning", "terminating"],
            "intent_scope": ["single_turn", "compound_task", "open_ended_research", "long_running_monitor", "operator_handoff"],
            "execution_surface": [
                "conversation",
                "retrieval",
                "workspace",
                "artifact",
                "durable_memory",
                "resident_queue",
                "transport_gateway",
                "browser_session",
                "system_state",
                "external_api",
                "database_connector",
                "cloud_connector",
                "workflow_engine",
                "knowledge_base",
                "planning_surface",
                "decision_support",
                "preference_surface",
                "media_input",
                "external_account_boundary",
                "human_world_unavailable",
            ],
            "evidence": [
                "not_required",
                "needed",
                "evidence_required",
                "citations_required",
                "partial",
                "sufficient",
                "insufficient",
                "conflicting",
            ],
            "tooling": ["respond_only", "host_tool_available", "permission_required", "not_configured", "planned"],
            "permissions": [
                "none_required",
                "read_allowed",
                "write_permission_required",
                "network_permission_required",
                "not_configured",
                "planned",
                "host_only",
                "dangerous_blocked",
            ],
            "memory": ["ephemeral_thread", "proposal_pending", "committed_snapshot", "deleted_or_expired"],
            "resident": ["interactive_turn", "queued_message", "scheduled_job", "waiting_for_user"],
            "network": ["offline", "structured_source_candidates", "live_fetch_allowlisted", "generic_search_configured", "blocked_by_policy"],
            "artifacts": ["none", "generated", "stored_blob", "redacted_preview", "exported"],
            "external_systems": ["not_connected", "transport_planned", "credential_required", "operator_approval_required"],
            "domain_profile": [
                "general",
                "finance_fundamentals",
                "academic_research",
                "scholarly_literature",
                "technical_research",
                "general_research_planning",
                "market_news",
                "macro_data_research",
                "competitive_intelligence",
                "legal_research",
                "contract_review",
                "medical_information",
                "data_analysis",
                "education_tutoring",
                "creative_or_roleplay",
                "communication_drafting",
                "operations_planning",
                "product_analysis",
                "risk_compliance_review",
                "cybersecurity_review",
                "database_query",
                "cloud_or_devops_boundary",
                "workflow_automation",
                "knowledge_base_maintenance",
                "multimodal_analysis",
                "portfolio_risk_research",
                "software_engineering",
                "strategy_decision_support",
                "personal_assistance",
                "quality_assurance",
            ],
            "output_contract": [
                "plain_answer",
                "cited_answer",
                "file_artifact",
                "structured_report",
                "failure_report",
                "failure_or_boundary_report",
                "ask_user",
            ],
            "route_class": [
                "respond_only",
                "executable_tool",
                "host_capability_or_response",
                "planned_or_not_configured_boundary",
                "host_only_boundary",
                "host_boundary",
            ],
            "user_control": ["normal", "interrupted", "cancelled", "clarification_requested"],
            "autonomy": [
                "single_turn_response",
                "bounded_task_loop",
                "long_running_resident_worker",
                "scheduled_monitor",
                "operator_review",
                "user_interrupted",
            ],
            "world_model": [
                "current_conversation",
                "thread_journal",
                "workspace_project",
                "web_corpus",
                "market_state",
                "durable_memory_snapshot",
                "external_account_boundary",
                "physical_world_unavailable",
                "database_or_cloud_boundary",
                "workflow_engine",
                "media_input",
            ],
            "resource_kind": [
                "conversation_turn",
                "web_page",
                "official_filing",
                "legal_source",
                "medical_source",
                "market_data",
                "news_article",
                "scholarly_source",
                "local_file",
                "generated_artifact",
                "memory_item",
                "queue_message",
                "calendar_event",
                "credential_boundary",
                "device_boundary",
                "learning_prompt",
                "task_plan",
                "decision_frame",
                "user_preference",
                "quality_checklist",
                "message_draft",
                "policy_document",
                "dataset",
                "database_table",
                "cloud_resource",
                "knowledge_base_entry",
                "media_input",
                "external_account",
                "system_state",
                "browser_session",
                "api_response",
                "workflow_run",
            ],
            "action_phase": [
                "intake",
                "decompose",
                "plan",
                "tool_call",
                "observe",
                "evaluate_progress",
                "replan",
                "synthesize",
                "commit_or_report",
                "await_user",
            ],
            "goal_structure": [
                "atomic",
                "compound_ordered",
                "compound_parallel",
                "open_ended",
                "recurring",
                "background_monitor",
                "human_world_request",
            ],
            "dependency_state": [
                "none",
                "depends_on_prior_step",
                "depends_on_external_data",
                "depends_on_user_input",
                "depends_on_permission",
                "depends_on_unconfigured_connector",
            ],
            "commitment_state": [
                "none",
                "drafting_commitment",
                "pending_user_approval",
                "active_commitment",
                "completed_commitment",
                "cancelled_commitment",
            ],
            "preference_state": [
                "not_relevant",
                "thread_preference",
                "durable_preference_candidate",
                "durable_preference_applied",
                "preference_conflict",
            ],
            "memory_scope": [
                "none",
                "current_turn",
                "thread_summary",
                "durable_snapshot",
                "proposal_shadow",
                "admin_review",
            ],
            "planning_depth": [
                "none",
                "single_action",
                "multi_step_plan",
                "research_plan",
                "resident_plan",
                "operator_review_plan",
            ],
            "operation_runtime": [
                "instant",
                "bounded_loop",
                "long_running",
                "scheduled",
                "resident",
                "external_handoff",
            ],
            "quality_bar": [
                "casual",
                "standard",
                "rigorous",
                "audit_ready",
                "regulated_domain",
            ],
            "interruption_policy": [
                "user_can_interrupt",
                "ask_only_if_blocked",
                "ask_before_side_effect",
                "operator_approval_required",
            ],
            "risk": [
                "none",
                "read",
                "write",
                "credential",
                "normal",
                "privacy_sensitive",
                "financial_advice_boundary",
                "legal_advice_boundary",
                "medical_boundary",
                "credential_boundary",
                "write_side_effect",
                "external_side_effect",
                "device_control_blocked",
                "host_only",
                "planned",
                "not_configured",
                "dangerous_blocked",
            ],
            "temporal": [
                "timeless",
                "current_time",
                "recent_news",
                "historical_period",
                "scheduled_future",
                "long_running",
            ],
            "authority": [
                "not_needed",
                "self_knowledge",
                "user_provided",
                "workspace_evidence",
                "retrieval_citation",
                "primary_source_required",
                "secondary_source_allowed",
                "conflicting_sources",
            ],
            "identity_boundary": [
                "assistant_self_description",
                "roleplay_persona",
                "professional_domain_role",
                "tool_capability_disclosure",
                "private_reasoning_blocked",
            ],
            "communication_channel": [
                "cli",
                "chat_thread",
                "resident_inbox",
                "transport_gateway_planned",
                "outbox_pending",
            ],
        },
        "task_domains": [
            "conversation",
            "roleplay",
            "technical_reasoning",
            "task_decomposition",
            "research_planning",
            "decision_support",
            "strategy_assessment",
            "personal_assistance",
            "preference_application",
            "quality_review",
            "retrieval_research",
            "finance_fundamentals",
            "academic_research",
            "scholarly_literature_review",
            "frontier_research",
            "market_news_research",
            "market_data_research",
            "macro_data_research",
            "competitive_intelligence",
            "financial_modeling",
            "document_drafting",
            "document_review",
            "report_generation",
            "email_drafting",
            "legal_research",
            "contract_review",
            "medical_information",
            "education_tutoring",
            "creative_writing",
            "communication_drafting",
            "customer_support_drafting",
            "operations_planning",
            "product_analysis",
            "risk_compliance_review",
            "cybersecurity_review",
            "code_review",
            "code_editing",
            "test_execution",
            "data_analysis",
            "spreadsheet_or_table_work",
            "database_query",
            "cloud_or_devops_boundary",
            "workflow_automation",
            "knowledge_base_maintenance",
            "multimodal_analysis",
            "project_management",
            "workspace_read",
            "workspace_write",
            "artifact_generation",
            "memory_admin",
            "knowledge_recall",
            "resident_operations",
            "long_running_monitoring",
            "transport_operations",
            "calendar_or_reminder",
            "notification_or_message_send",
            "browser_navigation_boundary",
            "external_api_integration",
            "system_observation",
            "environment_diagnostics",
            "credential_or_secret_boundary",
            "security_boundary",
            "physical_world_unavailable",
            "portfolio_risk_research",
            "general_problem_solving",
        ],
        "semantic_slots": {
            "domain": "what area the user task belongs to",
            "activity": "what the agent should do: answer, research, draft, inspect, monitor, write, route, or refuse",
            "resource": "what object is being worked on: web source, file, artifact, memory item, queue message, transport, device, or external API",
            "goal_structure": "whether the task is atomic, ordered, open-ended, recurring, or a human-world request",
            "dependency": "what the next step depends on: evidence, user input, permission, connector configuration, or prior observations",
            "commitment": "whether the agent is only planning, awaiting approval, actively executing, or done",
            "preference": "whether user preferences are thread-local, durable candidates, applied, or conflicting",
            "memory_scope": "whether the task uses current turn, thread summary, durable snapshot, shadow proposal, or admin review memory",
            "quality_bar": "how much rigor and auditability the answer or action requires",
            "capability": "host-visible capability id requested by the model packet",
            "permission": "host-owned permission or configuration boundary",
            "evidence": "whether cited retrieval/workspace/artifact evidence is needed",
            "output": "final answer, ask_user, artifact, failure report, or pending resident output",
        },
        "capability_statuses": [
            "enabled",
            "available_with_permission",
            "disabled",
            "not_configured",
            "planned",
            "host_only",
        ],
        "families": {
            "conversation": [
                "conversation.respond",
                "user.ask",
                "roleplay.perform",
                "knowledge.explain",
                "analysis.reason",
                "task.decompose",
                "decision.support",
                "strategy.assess",
                "personal_assistant.coordinate",
                "preference.apply",
            ],
            "workspace": ["workspace.list", "workspace.search", "workspace.file.read", "workspace.file.write"],
            "retrieval": ["retrieval.run", "research.plan", "web.research", "web.search", "web.fetch", "web.crawl", "browser.page.open"],
            "finance": [
                "finance.fundamentals_research",
                "finance.market_news",
                "finance.source_directory",
                "finance.market_data",
                "finance.macro_data",
                "finance.competitive_landscape",
            ],
            "academic": [
                "academic.research",
                "academic.frontier_research",
                "academic.literature_review",
                "academic.paper_search",
                "academic.scholarly_sources",
            ],
            "technical": [
                "technical.documentation_research",
                "technical.api_documentation",
                "technical.developer_docs",
                "technical.source_repository",
            ],
            "legal": ["legal.information", "legal.research", "contract.review"],
            "medical": ["medical.information", "medical.research"],
            "education": ["education.tutor"],
            "creative": ["creative.write", "roleplay.perform"],
            "communication": ["communication.draft", "communication.send", "email.draft"],
            "operations": ["operations.plan", "workflow.automation.plan"],
            "product": ["product.analysis", "document.draft", "report.compose"],
            "risk": ["risk.compliance_review", "quality.review", "finance.fundamentals_research"],
            "cybersecurity": ["cybersecurity.review", "code.read", "code.search"],
            "memory": ["durable_memory.read", "durable_memory.search", "durable_memory.propose", "durable_memory.commit", "durable_memory.delete", "durable_memory.export"],
            "artifact": ["artifact.create", "artifact.read", "artifact.export"],
            "document": ["document.draft", "document.review", "report.compose", "email.draft"],
            "data": ["calculator.compute", "finance.verify_numeric", "data.table.analyze", "data.transform", "chart.generate"],
            "database": ["database.query", "database.schema.inspect"],
            "code": ["code.search", "code.read", "code.patch", "test.run"],
            "cloud": ["cloud.resource.inspect", "cloud.deploy.boundary"],
            "workflow": ["workflow.automation.plan", "workflow.automation.run"],
            "knowledge_base": ["knowledge_base.search", "knowledge_base.maintain"],
            "multimodal": ["multimodal.image.analyze", "multimodal.document.ocr"],
            "project": ["project.plan", "project.status", "task.queue"],
            "resident": ["resident.inbox", "resident.outbox", "resident.scheduler", "resident.monitor"],
            "transport": ["transport.wechat", "transport.discord", "transport.slack", "transport.email"],
            "calendar": ["calendar.read", "calendar.schedule", "reminder.create"],
            "system": ["system.time", "system.environment", "system.process", "shell.exec"],
            "security": ["credential.read", "secret.store", "browser.session.attach", "device.input.control"],
        },
        "executable_tools_by_recipe": {
            "semantic_answer": [],
            "retrieval_answer": ["retrieval.run", "calculator.compute"],
            "workspace_answer": ["workspace.list", "workspace.search", "file.read"],
            "workspace_write": ["workspace.list", "workspace.search", "file.read", "workspace.write"],
            "system_answer": ["system.time"],
            "direct_answer": [],
            "clarify_first": [],
        },
        "not_default_or_requires_configuration": [
            "web.search",
            "web.fetch",
            "web.crawl",
            "network.fetch",
            "browser.page.open",
            "legal.research",
            "medical.research",
            "communication.send",
            "finance.market_news",
            "finance.market_data",
            "finance.macro_data",
            "shell.exec",
            "live_transport:*",
            "durable_memory.commit",
            "durable_memory.delete",
            "transport.*",
            "calendar.schedule",
            "database.query",
            "cloud.resource.inspect",
            "workflow.automation.run",
            "knowledge_base.maintain",
            "multimodal.image.analyze",
            "credential.read",
            "secret.store",
            "device.input.control",
        ],
    }


def compact_semantic_capability_catalog() -> JsonObject:
    """Provider-facing semantic catalog.

    The full semantic state space remains available through
    semantic_capability_catalog()/semantic_state_space_catalog() for host audit,
    state profiling, and UI. Semantic intake only needs the stable vocabulary
    that lets the model choose task modes, capability ids, and broad state axes.
    """

    catalog = semantic_capability_catalog()
    state_dimensions = catalog["state_dimensions"]
    selected_dimensions = (
        "execution_surface",
        "evidence",
        "permissions",
        "domain_profile",
        "route_class",
        "risk",
        "authority",
    )
    return {
        "version": catalog["version"],
        "modes": list(catalog["modes"]),
        "core_rule": catalog["core_rule"],
        "catalog_rule": catalog["catalog_rule"],
        "families": dict(catalog["families"]),
        "executable_tools_by_recipe": dict(catalog["executable_tools_by_recipe"]),
        "not_default_or_requires_configuration": list(catalog["not_default_or_requires_configuration"]),
        "state_dimensions": {
            key: list(state_dimensions[key])
            for key in selected_dimensions
            if key in state_dimensions
        },
        "state_dimension_keys": list(state_dimensions.keys()),
        "capability_statuses": list(catalog["capability_statuses"]),
    }


def semantic_state_space_catalog() -> JsonObject:
    catalog = semantic_capability_catalog()
    return {
        "version": catalog["version"],
        "modes": list(catalog["modes"]),
        "state_dimensions": dict(catalog["state_dimensions"]),
        "task_domains": list(catalog["task_domains"]),
        "families": dict(catalog["families"]),
        "semantic_slots": dict(catalog["semantic_slots"]),
        "not_default_or_requires_configuration": list(catalog["not_default_or_requires_configuration"]),
    }


def _base_capabilities() -> list[CapabilitySpec]:
    return [
        CapabilitySpec(
            capability_id="conversation.respond",
            family="conversation",
            status="enabled",
            description="Return a user-visible response through the host.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="user.ask",
            family="conversation",
            status="enabled",
            description="Ask the user for missing critical information.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="roleplay.perform",
            family="conversation",
            status="enabled",
            description="Answer in a user-requested role or persona inside the current thread.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="knowledge.explain",
            family="conversation",
            status="enabled",
            description="Explain general knowledge from model reasoning without tool execution.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="analysis.reason",
            family="conversation",
            status="enabled",
            description="Perform bounded reasoning from the current prompt/context without exposing private chain-of-thought.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="task.decompose",
            family="conversation",
            status="enabled",
            description="Decompose compound user goals into host-visible ordered intents and constraints.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="research.plan",
            family="retrieval",
            status="enabled",
            description="Plan research subquestions, source targets, evidence gaps, and stopping criteria without fetching by itself.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="decision.support",
            family="conversation",
            status="enabled",
            description="Frame options, tradeoffs, assumptions, and recommendation criteria from available context.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="strategy.assess",
            family="conversation",
            status="enabled",
            description="Assess strategic options and next moves without executing external side effects.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="personal_assistant.coordinate",
            family="conversation",
            status="enabled",
            description="Coordinate benign personal-assistant style planning inside the current conversation.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="preference.apply",
            family="conversation",
            status="enabled",
            description="Apply known thread or durable-memory preferences to response style and task handling.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="quality.review",
            family="risk",
            status="enabled",
            description="Review outputs, plans, or harness behavior against explicit quality criteria.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="legal.information",
            family="legal",
            status="enabled",
            description="Provide general legal information or role-framed legal reasoning without pretending to be licensed counsel.",
            enabled_by_default=True,
            metadata={"professional_boundary": "not_legal_advice"},
        ),
        CapabilitySpec(
            capability_id="legal.research",
            family="legal",
            status="available_with_permission",
            description="Research legal or regulatory sources through retrieval when jurisdiction/source evidence is required.",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"citations_recommended": True},
        ),
        CapabilitySpec(
            capability_id="contract.review",
            family="legal",
            status="enabled",
            description="Review user-provided contract text and identify issues without external legal representation.",
            enabled_by_default=True,
            metadata={"professional_boundary": "not_legal_advice"},
        ),
        CapabilitySpec(
            capability_id="medical.information",
            family="medical",
            status="enabled",
            description="Explain general medical information with safety limitations and without diagnosis or treatment directives.",
            enabled_by_default=True,
            metadata={"professional_boundary": "not_medical_advice"},
        ),
        CapabilitySpec(
            capability_id="medical.research",
            family="medical",
            status="available_with_permission",
            description="Research medical information through retrieval when current source evidence is required.",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"citations_recommended": True},
        ),
        CapabilitySpec(
            capability_id="education.tutor",
            family="education",
            status="enabled",
            description="Teach, explain, quiz, or coach within the current conversation.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="creative.write",
            family="creative",
            status="enabled",
            description="Write creative, roleplay, or light conversational content without external side effects.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="communication.draft",
            family="communication",
            status="enabled",
            description="Draft messages, replies, notifications, or customer-support text without sending them.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="communication.send",
            family="communication",
            status="planned",
            description="Send a message only through a future host-owned transport gateway.",
            side_effect_class="write",
            permissions_required=["transport:send"],
        ),
        CapabilitySpec(
            capability_id="operations.plan",
            family="operations",
            status="enabled",
            description="Plan procedures, runbooks, workflows, or operating checklists without executing external systems.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="product.analysis",
            family="product",
            status="enabled",
            description="Analyze product requirements, tradeoffs, roadmap options, or user workflows from available context.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="risk.compliance_review",
            family="risk",
            status="enabled",
            description="Review risks, controls, compliance posture, or decision boundaries from supplied context.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="cybersecurity.review",
            family="cybersecurity",
            status="enabled",
            description="Perform defensive security review of user-provided context without offensive execution.",
            enabled_by_default=True,
            metadata={"professional_boundary": "defensive_only"},
        ),
        CapabilitySpec(
            capability_id="document.draft",
            family="document",
            status="enabled",
            description="Draft user-visible text in the response; file writes still require workspace.write.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="document.review",
            family="document",
            status="enabled",
            description="Review provided text or context and return comments without mutating files.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="report.compose",
            family="document",
            status="enabled",
            description="Compose a structured report in the response from available context/evidence.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="email.draft",
            family="document",
            status="enabled",
            description="Draft an email/message body in the response without sending it.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="finance.fundamentals_research",
            family="finance",
            status="enabled",
            description="Use the finance fundamentals profile to prefer filings, exchange disclosures, company IR, and official statistics.",
            enabled_by_default=True,
            metadata={"research_profile_id": "finance_fundamentals"},
        ),
        CapabilitySpec(
            capability_id="finance.source_directory",
            family="finance",
            status="enabled",
            description="Describe authoritative source families and where the agent should search for fundamentals evidence.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="finance.market_news",
            family="finance",
            status="available_with_permission",
            description="Current market news research with source/date constraints through retrieval.run and configured source/fetch providers.",
            side_effect_class="network",
            permissions_required=["network:fetch"],
        ),
        CapabilitySpec(
            capability_id="finance.market_data",
            family="finance",
            status="available_with_permission",
            description="Market price, quote, and time-series research through approved retrieval or market-data providers.",
            side_effect_class="network",
            permissions_required=["network:fetch"],
        ),
        CapabilitySpec(
            capability_id="finance.macro_data",
            family="finance",
            status="available_with_permission",
            description="Official macroeconomic, central-bank, Treasury, and economic-indicator research through approved retrieval providers.",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"research_profile_id": "finance_fundamentals"},
        ),
        CapabilitySpec(
            capability_id="finance.competitive_landscape",
            family="finance",
            status="enabled",
            description="Research a company's competitive landscape through grounded retrieval when sources are required.",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"research_profile_id": "finance_fundamentals"},
        ),
        CapabilitySpec(
            capability_id="academic.research",
            family="academic",
            status="available_with_permission",
            description="Scholarly research through retrieval.run with paper, preprint, publisher, and academic-index source preference.",
            tool_name="retrieval.run",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"research_profile_id": "academic_research"},
        ),
        CapabilitySpec(
            capability_id="academic.frontier_research",
            family="academic",
            status="available_with_permission",
            description="Frontier or recent scholarly research requiring recent papers, surveys, open questions, and source-backed limitations.",
            tool_name="retrieval.run",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"research_profile_id": "academic_research"},
        ),
        CapabilitySpec(
            capability_id="academic.literature_review",
            family="academic",
            status="available_with_permission",
            description="Literature review over scholarly papers, surveys, bibliographic indexes, and publisher/preprint pages.",
            tool_name="retrieval.run",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"research_profile_id": "academic_research"},
        ),
        CapabilitySpec(
            capability_id="academic.paper_search",
            family="academic",
            status="available_with_permission",
            description="Search for specific papers, authors, DOI/arXiv identifiers, venues, and publication metadata.",
            tool_name="retrieval.run",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"research_profile_id": "academic_research"},
        ),
        CapabilitySpec(
            capability_id="academic.scholarly_sources",
            family="academic",
            status="enabled",
            description="Describe and prefer scholarly source families such as arXiv, journal publishers, OpenAlex, Crossref, DBLP, and Semantic Scholar.",
            enabled_by_default=True,
            metadata={"research_profile_id": "academic_research"},
        ),
        CapabilitySpec(
            capability_id="technical.documentation_research",
            family="technical",
            status="enabled",
            description="Use the technical documentation profile to prefer official docs, source repositories, standards, and developer references.",
            enabled_by_default=True,
            metadata={"research_profile_id": "technical_documentation"},
        ),
        CapabilitySpec(
            capability_id="technical.api_documentation",
            family="technical",
            status="available_with_permission",
            description="Research API endpoints, authentication, parameters, response schemas, examples, rate limits, and pricing through retrieval.run.",
            tool_name="retrieval.run",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"research_profile_id": "technical_documentation"},
        ),
        CapabilitySpec(
            capability_id="technical.developer_docs",
            family="technical",
            status="available_with_permission",
            description="Research developer documentation and platform guides through retrieval.run.",
            tool_name="retrieval.run",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"research_profile_id": "technical_documentation"},
        ),
        CapabilitySpec(
            capability_id="technical.source_repository",
            family="technical",
            status="available_with_permission",
            description="Use source repository documentation or README evidence when official docs are unavailable or repository docs are requested.",
            tool_name="retrieval.run",
            side_effect_class="network",
            permissions_required=["network:fetch"],
            metadata={"research_profile_id": "technical_documentation"},
        ),
        CapabilitySpec(
            capability_id="web.research",
            family="retrieval",
            status="available_with_permission",
            description="General web research through retrieval.run when a search/fetch provider is configured.",
            tool_name="retrieval.run",
            side_effect_class="network",
            permissions_required=["network:fetch"],
        ),
        CapabilitySpec(
            capability_id="workspace.file.write",
            family="workspace",
            status="available_with_permission",
            description="Write workspace files through host policy and artifact/journal redaction.",
            tool_name="workspace.write",
            side_effect_class="write",
            permissions_required=["workspace:write"],
        ),
        CapabilitySpec(
            capability_id="web.search",
            family="retrieval",
            status="not_configured",
            description="Live web search provider. Requires explicit endpoint/provider configuration.",
            side_effect_class="network",
            permissions_required=["network:fetch"],
        ),
        CapabilitySpec(
            capability_id="web.fetch",
            family="retrieval",
            status="available_with_permission",
            description="Fetch a host-approved URL through bounded HTTP fetch providers.",
            tool_name="network.fetch",
            side_effect_class="network",
            permissions_required=["network:fetch"],
        ),
        CapabilitySpec(
            capability_id="web.crawl",
            family="retrieval",
            status="planned",
            description="Bounded crawl/page expansion capability for research workflows.",
            side_effect_class="network",
            permissions_required=["network:fetch"],
        ),
        CapabilitySpec(
            capability_id="browser.page.open",
            family="retrieval",
            status="planned",
            description="Open and inspect a browser/page representation through a bounded page provider.",
            side_effect_class="network",
            permissions_required=["network:fetch"],
        ),
        CapabilitySpec(
            capability_id="durable_memory.read",
            family="memory",
            status="host_only",
            description="Read committed durable memory into context snapshots.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="durable_memory.search",
            family="memory",
            status="enabled",
            description="Recall committed durable memory through host-scoped context injection and memory admin APIs.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="durable_memory.propose",
            family="memory",
            status="enabled",
            description="Create reviewable memory proposals from semantic intake and observations.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="durable_memory.commit",
            family="memory",
            status="host_only",
            description="Commit approved memory proposals. The model cannot directly commit memory.",
            permissions_required=["durable_memory:write"],
        ),
        CapabilitySpec(
            capability_id="durable_memory.delete",
            family="memory",
            status="host_only",
            description="Delete or tombstone committed memory through explicit user/admin action.",
            permissions_required=["durable_memory:delete"],
        ),
        CapabilitySpec(
            capability_id="durable_memory.export",
            family="memory",
            status="host_only",
            description="Export durable memory and provenance for audit.",
            permissions_required=["durable_memory:export"],
        ),
        CapabilitySpec(
            capability_id="artifact.create",
            family="artifact",
            status="enabled",
            description="Create host-visible generated artifacts through approved response or workspace-write paths.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="artifact.read",
            family="artifact",
            status="enabled",
            description="Read artifact previews and references already exposed by the host context.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="artifact.export",
            family="artifact",
            status="planned",
            description="Export artifact bundles through a host-approved export surface.",
            side_effect_class="write",
            permissions_required=["artifact:export"],
        ),
        CapabilitySpec(
            capability_id="data.table.analyze",
            family="data",
            status="planned",
            description="Analyze structured tables or datasets through bounded data tools.",
            side_effect_class="read",
        ),
        CapabilitySpec(
            capability_id="data.transform",
            family="data",
            status="planned",
            description="Transform structured data into derived files or artifacts under host policy.",
            side_effect_class="write",
            permissions_required=["workspace:write"],
        ),
        CapabilitySpec(
            capability_id="chart.generate",
            family="data",
            status="planned",
            description="Generate chart artifacts from grounded data.",
            side_effect_class="write",
            permissions_required=["workspace:write"],
        ),
        CapabilitySpec(
            capability_id="database.query",
            family="database",
            status="planned",
            description="Query an approved database through a bounded connector with schema-aware limits.",
            side_effect_class="read",
            permissions_required=["database:read"],
        ),
        CapabilitySpec(
            capability_id="database.schema.inspect",
            family="database",
            status="planned",
            description="Inspect approved database schemas without exposing credentials or unrestricted data.",
            side_effect_class="read",
            permissions_required=["database:read"],
        ),
        CapabilitySpec(
            capability_id="code.search",
            family="code",
            status="available_with_permission",
            description="Search repository code through workspace search.",
            tool_name="workspace.search",
            side_effect_class="read",
        ),
        CapabilitySpec(
            capability_id="code.read",
            family="code",
            status="available_with_permission",
            description="Read repository code through file.read.",
            tool_name="file.read",
            side_effect_class="read",
        ),
        CapabilitySpec(
            capability_id="code.patch",
            family="code",
            status="planned",
            description="Apply code patches through a bounded edit tool with diff review.",
            side_effect_class="write",
            permissions_required=["workspace:write"],
        ),
        CapabilitySpec(
            capability_id="test.run",
            family="code",
            status="planned",
            description="Run tests through an allowlisted command runner.",
            side_effect_class="shell",
            permissions_required=["shell:exec"],
        ),
        CapabilitySpec(
            capability_id="cloud.resource.inspect",
            family="cloud",
            status="planned",
            description="Inspect approved cloud resources through a host connector with redacted credentials.",
            side_effect_class="read",
            permissions_required=["cloud:read"],
        ),
        CapabilitySpec(
            capability_id="cloud.deploy.boundary",
            family="cloud",
            status="planned",
            description="Represent cloud deployment requests as high-risk boundaries until an explicit deploy operator exists.",
            side_effect_class="destructive",
            permissions_required=["cloud:deploy"],
        ),
        CapabilitySpec(
            capability_id="workflow.automation.plan",
            family="workflow",
            status="enabled",
            description="Draft a host-visible workflow automation plan without executing external side effects.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="workflow.automation.run",
            family="workflow",
            status="planned",
            description="Run workflow automations only through a future host-owned automation engine.",
            side_effect_class="write",
            permissions_required=["workflow:run"],
        ),
        CapabilitySpec(
            capability_id="knowledge_base.search",
            family="knowledge_base",
            status="planned",
            description="Search a configured project or organization knowledge base.",
            side_effect_class="read",
            permissions_required=["knowledge_base:read"],
        ),
        CapabilitySpec(
            capability_id="knowledge_base.maintain",
            family="knowledge_base",
            status="planned",
            description="Propose or apply knowledge-base updates through host review and provenance.",
            side_effect_class="write",
            permissions_required=["knowledge_base:write"],
        ),
        CapabilitySpec(
            capability_id="multimodal.image.analyze",
            family="multimodal",
            status="planned",
            description="Analyze approved image inputs through a multimodal processor or tool.",
            side_effect_class="read",
            permissions_required=["multimodal:read"],
        ),
        CapabilitySpec(
            capability_id="multimodal.document.ocr",
            family="multimodal",
            status="planned",
            description="Extract text from approved document images through an OCR provider.",
            side_effect_class="read",
            permissions_required=["multimodal:read"],
        ),
        CapabilitySpec(
            capability_id="project.plan",
            family="project",
            status="enabled",
            description="Maintain a host-visible task plan for the current run.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="project.status",
            family="project",
            status="enabled",
            description="Report current task, run, thread, and plan status from journal-derived state.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="task.queue",
            family="project",
            status="host_only",
            description="Represent queued resident or scheduled tasks without letting the model mutate the queue directly.",
        ),
        CapabilitySpec(
            capability_id="resident.inbox",
            family="resident",
            status="enabled",
            description="Queue incoming local resident messages.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="resident.outbox",
            family="resident",
            status="enabled",
            description="Record resident outputs for delivery/acknowledgement.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="resident.scheduler",
            family="resident",
            status="enabled",
            description="Run local scheduled resident jobs through the host queue.",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="resident.monitor",
            family="resident",
            status="planned",
            description="Monitor local resident worker health and queued work.",
        ),
        CapabilitySpec(
            capability_id="transport.wechat",
            family="transport",
            status="planned",
            description="External WeChat transport integration. Not a kernel decision layer.",
            permissions_required=["live_transport:wechat"],
        ),
        CapabilitySpec(
            capability_id="transport.discord",
            family="transport",
            status="planned",
            description="External Discord transport integration. Not a kernel decision layer.",
            permissions_required=["live_transport:discord"],
        ),
        CapabilitySpec(
            capability_id="transport.slack",
            family="transport",
            status="planned",
            description="External Slack transport integration. Not a kernel decision layer.",
            permissions_required=["live_transport:slack"],
        ),
        CapabilitySpec(
            capability_id="transport.email",
            family="transport",
            status="planned",
            description="External email transport integration through a host gateway.",
            permissions_required=["live_transport:email"],
        ),
        CapabilitySpec(
            capability_id="calendar.read",
            family="calendar",
            status="planned",
            description="Read calendar state through an approved calendar connector.",
            side_effect_class="read",
            permissions_required=["calendar:read"],
        ),
        CapabilitySpec(
            capability_id="calendar.schedule",
            family="calendar",
            status="planned",
            description="Create or update calendar events through an approved connector.",
            side_effect_class="write",
            permissions_required=["calendar:write"],
        ),
        CapabilitySpec(
            capability_id="reminder.create",
            family="calendar",
            status="planned",
            description="Create reminders through the resident scheduler or future calendar connector.",
            side_effect_class="write",
            permissions_required=["resident:schedule"],
        ),
        CapabilitySpec(
            capability_id="system.time",
            family="system",
            status="enabled",
            description="Host time tool for current time and timezone-aware responses.",
            tool_name="system.time",
            side_effect_class="read",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="system.environment",
            family="system",
            status="enabled",
            description="Safe run/thread/context state already exposed by the host, with secrets redacted.",
            side_effect_class="read",
            enabled_by_default=True,
        ),
        CapabilitySpec(
            capability_id="system.process",
            family="system",
            status="planned",
            description="Read bounded process/runtime diagnostics without exposing secrets.",
            side_effect_class="read",
        ),
        CapabilitySpec(
            capability_id="shell.exec",
            family="system",
            status="available_with_permission",
            description="Bounded shell execution with explicit executable allowlist.",
            tool_name="shell.exec",
            side_effect_class="shell",
            permissions_required=["shell:exec"],
        ),
        CapabilitySpec(
            capability_id="credential.read",
            family="security",
            status="host_only",
            description="Read credentials only through host-owned secret providers; model-visible context never receives raw secrets.",
            permissions_required=["secret:read"],
        ),
        CapabilitySpec(
            capability_id="secret.store",
            family="security",
            status="host_only",
            description="Store secrets only through a dedicated host secret store, not journal or memory.",
            permissions_required=["secret:write"],
        ),
        CapabilitySpec(
            capability_id="browser.session.attach",
            family="security",
            status="planned",
            description="Attach to a user browser/session only through explicit host authorization.",
            side_effect_class="network",
            permissions_required=["browser:attach"],
        ),
        CapabilitySpec(
            capability_id="device.input.control",
            family="security",
            status="planned",
            description="Control local mouse/keyboard or physical devices only through a future high-risk operator.",
            side_effect_class="destructive",
            permissions_required=["device:control"],
        ),
    ]


def _tool_capabilities(
    manifests: dict[str, ToolManifest],
    allowed_tools: set[str],
    allowed_permissions: set[str],
) -> list[CapabilitySpec]:
    result: list[CapabilitySpec] = []
    mappings = {
        "retrieval.run": ("retrieval.run", "retrieval", "Run bounded retrieval FSM and produce evidence/citations."),
        "workspace.list": ("workspace.list", "workspace", "List workspace directory entries."),
        "workspace.search": ("workspace.search", "workspace", "Search workspace files."),
        "file.read": ("workspace.file.read", "workspace", "Read a workspace file."),
        "workspace.write": ("workspace.file.write", "workspace", "Write a workspace file under host policy."),
        "network.fetch": ("web.fetch", "retrieval", "Fetch a URL through a bounded network tool."),
        "shell.exec": ("shell.exec", "system", "Execute an allowlisted shell command."),
        "system.time": ("system.time", "system", "Read current host time with an explicit timezone."),
        "memory.recall": ("durable_memory.search", "memory", "Recall committed workspace/project and thread memory."),
        "calculator.compute": ("calculator.compute", "data", "Evaluate deterministic numeric expressions from model-proposed, evidence-backed inputs."),
        "finance.verify_numeric": ("finance.verify_numeric", "data", "Verify model-proposed finance numeric claims against provided facts, formula traces, citations, and evidence."),
        "finance.toolchain.describe": ("finance.toolchain.describe", "finance", "Inspect optional mature finance components registered in the Holo toolchain."),
        "sec.edgar.company_filings": ("sec.edgar.company_filings", "finance", "Use EdgarTools to discover SEC issuer filings under host network policy."),
        "sec.edgar.financials": ("sec.edgar.financials", "finance", "Use EdgarTools SEC/XBRL financial statement candidates for model-owned fact binding."),
        "document.docling.convert": ("document.docling.convert", "retrieval", "Use Docling to convert URL documents and tables into structured text candidates."),
        "document.trafilatura.extract": ("document.trafilatura.extract", "retrieval", "Use Trafilatura to extract readable text candidates from URL or HTML documents."),
        "market.openbb.fetch": ("market.openbb.fetch", "finance", "Use allowlisted OpenBB routes for external market and fundamental data."),
        "data.table.query": ("data.table.query", "data", "Use DuckDB/Pandas for read-only SQL over model-provided evidence tables."),
        "math.sympy.compute": ("math.sympy.compute", "data", "Use SymPy for model-proposed symbolic or high-precision math."),
    }
    for tool_name, manifest in manifests.items():
        capability_id, family, description = mappings.get(
            tool_name,
            (f"tool.{tool_name}", manifest.resource_kind or "tool", manifest.description),
        )
        required = set(manifest.permissions_required)
        allowed = not required or required.issubset(allowed_permissions) or tool_name in allowed_tools
        if not manifest.enabled:
            status = "disabled"
        elif allowed:
            status = "enabled"
        else:
            status = "available_with_permission"
        result.append(
            CapabilitySpec(
                capability_id=capability_id,
                family=family,
                status=status,
                description=description,
                tool_name=tool_name,
                side_effect_class=manifest.side_effect_class,
                permissions_required=list(manifest.permissions_required),
                enabled_by_default=manifest.enabled and status == "enabled",
                metadata={
                    "resource_kind": manifest.resource_kind,
                    "operator_kind": manifest.operator_kind,
                    "input_schema": manifest.input_schema,
                },
            )
        )
    return result


def _family_summary(specs: list[CapabilitySpec]) -> dict[str, dict[str, int]]:
    summary: dict[str, dict[str, int]] = {}
    for spec in specs:
        family = summary.setdefault(spec.family, {})
        family[spec.status] = family.get(spec.status, 0) + 1
    return summary
