from __future__ import annotations

from ..policies import MIND_GRAPH_DEFAULTS, policy_copy

STREAM_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.stream_defaults)
GAME_STATE_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.game_state_defaults)
AFFECT_STATE_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.affect_state_defaults)
DRIVE_STATE_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.drive_state_defaults)
VALUE_STATE_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.value_state_defaults)
CONFLICT_STATE_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.conflict_state_defaults)
RESISTANCE_POSTURE_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.resistance_posture_defaults)
WORLD_CONTACT_MODEL_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.world_contact_model_defaults)
WORLD_THREAD_MODEL_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.world_thread_model_defaults)
AUTOBIOGRAPHICAL_STABLE_TRAITS_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.autobiographical_stable_traits_defaults)
AUTOBIOGRAPHICAL_CHAPTER_DEFAULT = MIND_GRAPH_DEFAULTS.autobiographical_chapter_default
GOAL_TYPE_DEFAULT_PRIORITIES = policy_copy(MIND_GRAPH_DEFAULTS.goal_type_default_priorities)
BRAIN_LOOP_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.brain_loop_defaults)
WORLD_EXPRESSION_SIGNAL_DEFAULTS = policy_copy(MIND_GRAPH_DEFAULTS.world_expression_signal_defaults)
ACTION_CALIBRATION_HISTORY_LIMIT = MIND_GRAPH_DEFAULTS.action_calibration_history_limit
ACTION_CALIBRATION_RECENT_WINDOW_HOURS = MIND_GRAPH_DEFAULTS.action_calibration_recent_window_hours
ACTION_CALIBRATION_RECENT_METRICS_LIMIT = MIND_GRAPH_DEFAULTS.action_calibration_recent_metrics_limit
