from __future__ import annotations

from pathlib import Path

from kernel_v3.contracts import JsonObject
from kernel_v3.finance.open_components import isolated_component_status


FINANCE_TOOL_WORKERS_SCHEMA = "holo.kernel_v3.finance_tool_workers.v1"

FINANCE_COMPONENT_WORKER_SPECS: dict[str, JsonObject] = {
    "documents": {
        "component": "docling",
        "purpose": "document/PDF/HTML table conversion for document.docling.convert",
        "env_var": "HOLO_DOCLING_PYTHON",
        "requirements": "requirements-finance-isolated-documents.txt",
        "default_dir": "documents",
    },
    "market": {
        "component": "openbb",
        "purpose": "market/fundamental data for market.openbb.fetch",
        "env_var": "HOLO_OPENBB_PYTHON",
        "requirements": "requirements-finance-isolated-market.txt",
        "default_dir": "market",
    },
}


def build_finance_tool_worker_status(
    *,
    root: Path | str = ".state/kernel_v3/finance-workers",
    write_setup: bool = False,
) -> JsonObject:
    root_path = Path(root)
    workers = []
    for worker_id, spec in FINANCE_COMPONENT_WORKER_SPECS.items():
        component = str(spec["component"])
        worker_dir = root_path / str(spec["default_dir"])
        python_path = worker_dir / ".venv" / "bin" / "python"
        status = isolated_component_status(component)
        configured = bool(status.get("configured"))
        package_available = bool(status.get("package_available"))
        ready = configured and package_available
        workers.append(
            {
                "worker_id": worker_id,
                "component": component,
                "purpose": spec["purpose"],
                "status": "ready" if ready else ("configured_but_package_missing" if configured else "not_configured"),
                "ready": ready,
                "env_var": spec["env_var"],
                "configured_python": status.get("python"),
                "package_available": status.get("package_available"),
                "package_probe_error": status.get("package_probe_error"),
                "recommended_python": str(python_path),
                "requirements": spec["requirements"],
                "setup_commands": _setup_commands(root_path=root_path, spec=spec),
                "export_command": f"export {spec['env_var']}={python_path}",
            }
        )
    missing = [item["worker_id"] for item in workers if not item["ready"]]
    payload: JsonObject = {
        "schema": FINANCE_TOOL_WORKERS_SCHEMA,
        "status": "ok" if not missing else "attention",
        "root": str(root_path),
        "workers": workers,
        "missing_workers": missing,
        "host_boundary": (
            "This command only inspects and explains isolated worker configuration. "
            "It does not install packages, run benchmarks, or claim finance capability."
        ),
    }
    if write_setup:
        payload["setup_artifacts"] = write_finance_tool_worker_setup(root=root_path, workers=workers)
    return payload


def write_finance_tool_worker_setup(*, root: Path | str = ".state/kernel_v3/finance-workers", workers: list[JsonObject] | None = None) -> JsonObject:
    root_path = Path(root)
    root_path.mkdir(parents=True, exist_ok=True)
    if workers is None:
        workers = [
            {
                "worker_id": worker_id,
                "setup_commands": _setup_commands(root_path=root_path, spec=spec),
                "export_command": f"export {spec['env_var']}={root_path / str(spec['default_dir']) / '.venv' / 'bin' / 'python'}",
            }
            for worker_id, spec in FINANCE_COMPONENT_WORKER_SPECS.items()
        ]
    script_path = root_path / "setup-finance-workers.sh"
    env_path = root_path / "finance-workers.env"
    script_lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by Holo Kernel v3 finance-tool-workers.",
        "# Review before running. This installs heavy components into isolated venvs only.",
        "",
    ]
    env_lines = [
        "# Generated by Holo Kernel v3 finance-tool-workers.",
        "# Source this file after the isolated workers are installed.",
        "",
    ]
    for worker in workers:
        if not isinstance(worker, dict):
            continue
        script_lines.append(f"# {worker.get('worker_id')}")
        for command in _string_list(worker.get("setup_commands")):
            script_lines.append(command)
        script_lines.append("")
        export_command = str(worker.get("export_command") or "")
        if export_command:
            env_lines.append(export_command)
    script_path.write_text("\n".join(script_lines).rstrip() + "\n", encoding="utf-8")
    script_path.chmod(0o755)
    env_path.write_text("\n".join(env_lines).rstrip() + "\n", encoding="utf-8")
    return {
        "status": "written",
        "script_path": str(script_path),
        "env_path": str(env_path),
        "host_boundary": "setup artifacts only; no package installation was executed by Holo",
    }


def render_finance_tool_worker_status(payload: JsonObject) -> str:
    lines = [
        f"Finance tool workers: {payload.get('status')}",
        f"root={payload.get('root')}",
        "capability_claim=false; benchmark_progress_claim=false",
        "",
        "Workers:",
    ]
    for item in payload.get("workers", []):
        if not isinstance(item, dict):
            continue
        lines.append(
            "- "
            + f"{item.get('worker_id')} component={item.get('component')} status={item.get('status')} "
            + f"env={item.get('env_var')} configured_python={item.get('configured_python')}"
        )
        if item.get("status") != "ready":
            lines.append(f"  requirements={item.get('requirements')}")
            lines.append(f"  export={item.get('export_command')}")
    artifacts = payload.get("setup_artifacts")
    if isinstance(artifacts, dict):
        lines.extend(
            [
                "",
                "Setup artifacts:",
                f"- script={artifacts.get('script_path')}",
                f"- env={artifacts.get('env_path')}",
            ]
        )
    return "\n".join(lines)


def _setup_commands(*, root_path: Path, spec: JsonObject) -> list[str]:
    worker_dir = root_path / str(spec["default_dir"])
    python_path = worker_dir / ".venv" / "bin" / "python"
    return [
        f"python -m venv {worker_dir / '.venv'}",
        f"{python_path} -m pip install -r {spec['requirements']}",
        f"export {spec['env_var']}={python_path}",
    ]


def _string_list(value) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item)]
    if isinstance(value, tuple):
        return [str(item) for item in value if str(item)]
    return []
