from kernel_v3.processors.contracts import (
    CHAT_ROUTE_PROMPT_CONTRACT,
    CHAT_ROUTE_SCHEMA,
    EVALUATOR_PROMPT_CONTRACT,
    EVALUATOR_SCHEMA,
    PLANNER_PROMPT_CONTRACT,
    PLANNER_SCHEMA,
    SEMANTIC_INTAKE_PROMPT_CONTRACT,
    SEMANTIC_INTAKE_SCHEMA,
    SYNTHESIZER_PROMPT_CONTRACT,
    SYNTHESIZER_SCHEMA,
    FinalAnswer,
    JsonSchema,
    MISSION_ASSESS_PROMPT_CONTRACT,
    MISSION_ASSESS_SCHEMA,
    ProcessorOutcome,
    ProcessorProvider,
    ProcessorRoute,
)
from kernel_v3.processors.adapters import ModelEvaluator, ModelPlanner, Synthesizer
from kernel_v3.processors.fabric import ProcessorFabric
from kernel_v3.processors.generation import LATENCY_TARGETS, adapt_generation_parameters
from kernel_v3.processors.providers import (
    DeepSeekProvider,
    FakeJsonProvider,
    FakeMalformedJsonProvider,
    FakeTimeoutProvider,
    OpenAICompatibleProvider,
    PROCESSOR_SYSTEM_PROMPT,
)
from kernel_v3.processors.routing import (
    DEEPSEEK_LEGACY_REASONER,
    DEEPSEEK_V4_FLASH,
    DEEPSEEK_V4_PRO,
    ProcessorRouter,
    deepseek_v4_router,
    deepseek_v4_routes,
)
from kernel_v3.processors.scenarios import (
    SemanticScenario,
    SemanticScenarioResult,
    deepseek_v4_semantic_scenarios,
    run_semantic_scenarios,
    scenario_report_payload,
    validate_semantic_scenario,
)

__all__ = [
    "CHAT_ROUTE_PROMPT_CONTRACT",
    "CHAT_ROUTE_SCHEMA",
    "DeepSeekProvider",
    "DEEPSEEK_LEGACY_REASONER",
    "DEEPSEEK_V4_FLASH",
    "DEEPSEEK_V4_PRO",
    "EVALUATOR_PROMPT_CONTRACT",
    "EVALUATOR_SCHEMA",
    "FakeJsonProvider",
    "FakeMalformedJsonProvider",
    "FakeTimeoutProvider",
    "FinalAnswer",
    "JsonSchema",
    "LATENCY_TARGETS",
    "MISSION_ASSESS_PROMPT_CONTRACT",
    "MISSION_ASSESS_SCHEMA",
    "ModelEvaluator",
    "ModelPlanner",
    "OpenAICompatibleProvider",
    "PLANNER_PROMPT_CONTRACT",
    "PLANNER_SCHEMA",
    "PROCESSOR_SYSTEM_PROMPT",
    "ProcessorFabric",
    "ProcessorOutcome",
    "ProcessorProvider",
    "ProcessorRoute",
    "ProcessorRouter",
    "SEMANTIC_INTAKE_PROMPT_CONTRACT",
    "SEMANTIC_INTAKE_SCHEMA",
    "adapt_generation_parameters",
    "deepseek_v4_router",
    "deepseek_v4_routes",
    "SYNTHESIZER_PROMPT_CONTRACT",
    "SYNTHESIZER_SCHEMA",
    "Synthesizer",
    "SemanticScenario",
    "SemanticScenarioResult",
    "deepseek_v4_semantic_scenarios",
    "run_semantic_scenarios",
    "scenario_report_payload",
    "validate_semantic_scenario",
]
